version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: vesi_app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-lib:/var/lib/letsencrypt
      - ./public:/public
    environment:
      - NODE_ENV=production 